---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  namespace: rook-ceph
  name: rook-ceph
spec:
  interval: 1h
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        namespace: flux-system
        name: rook-ceph
      # renovate: registryUrl=https://charts.rook.io/release
      chart: rook-ceph
      version: v1.9.3
  values:
    rbacEnabled: true
    pspEnable: true
    crds:
      enabled: false
    csi:
      enableRbdDriver: false
      enableRBDSnapshotter: false
    resources:
      limits:
        cpu: 1
        memory: 512Mi
      requests:
        cpu: 0.1
        memory: 128Mi
