creation_rules:
  # -- The subkey 1CFC8FF236EC0896 would expire on 2023-06-19
  # ansible secrets
  - pgp: 1CFC8FF236EC0896
    path_regex: ansible/project/.*\.sops\.(yml|yaml)$
    encrypted_regex: ([Pp]assword)
  # cluster secrets
  - pgp: 1CFC8FF236EC0896
    path_regex: shed-cluster/.*secret\.(yml|yaml)$
    encrypted_regex: (^data$|^stringData$|user|[Pp]assword|userDatabase)
  # terraform secrets
  - pgp: 1CFC8FF236EC0896
    path_regex: terraform/.*\.sops\.(yml|yaml)$
