creation_rules:
    # -- The subkey 1CFC8FF236EC0896 would expire on 2023-06-19
    # ansible secrets
    - pgp: 1CFC8FF236EC0896
      path_regex: ansible/project/.*\.sops\.(yml|yaml)$
      encrypted_regex: ([Pp]assword)
