ansible_host: 192.168.253.2
ansible_user: ubuntu
ansible_password: ENC[AES256_GCM,data:bNAGAAznCZA=,iv:V9fGt4/OY3cXQWzKuXARmz+URCKjoAwv/KypaAlpSJM=,tag:mTK4d63tOvu+9cXDK9lJCg==,type:str]
ansible_become_password: ENC[AES256_GCM,data:hE2s8KgkdV2tOwc2IZnTaKvfvbKOTw==,iv:L14pW4GIsNqKVRK5AJbMqFHOpAO2vOvAFb7ShscleBc=,tag:izZqYSCWUNvYZ15pPxH4Mg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-06-19T16:09:23Z"
    mac: ENC[AES256_GCM,data:TRYdh9w/dG2HRgPJzWvCMsUEpVs2bfQvMaC9gLqFe1EpjfG/F7XN4wtW9heNAaKokxrET8hgubiITBz560Pr5JMyYhQvjudxtjUkWWQhmaBwtx3OPfqYai3N1HlfoaT8yssxGiQUYGfPXt3IE4R5ofZavEReMZv23nAamwgtU90=,iv:eQPelg4y9L40H1hF/6jaCuRXxHMojQhQddajb/nqebE=,tag:Ghzx0lfUW1EDwLO3/rolUg==,type:str]
    pgp:
        - created_at: "2022-06-19T16:09:22Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMAxz8j/I27AiWAQv9EzdGeCLpVc9YA7BL0bFZ4TqroJ+sy0wpdJZ1KLIW1Bci
            cTpjDQcYy2RQdiR+Xzxc0nfg8Yi9ZtHsRRGN4kauE4x+M2THaiJ7Evdz+EbGHvlR
            OlF7SWCgdf2vnCF9yVBZk42kdB/wu4u8MkosP1CMhU+Zi0vT1iRjE43xonR6CtoF
            AspQDB8cUNKGG+2n871TcObgePPrZvWdMfWxs8N/6XguW7EHJJxLtZwMc39MLFPG
            DocwKrA6aK+CnTG96SgNnCu6XZNSogJsVMlaAaWquJrc7G4dAoOnhzWPw1KbvFTk
            0nwNYuee2M/F2299tmuD9kCaYkqa7cCHAhw+EEIakJpQSpwfgt2oWLYF4WpnboJS
            EJz5FNuX2JOpFG4Ecp/lN4RuivuRGWG2SFRMKsxRbdee2GfxbtlTtRbMBZ8B/q4N
            IwsayNxbDmy3wJ0l7JuYHAtlJKjsVBo35i5r+jbtCyzPjOvBLUYx5jP3Nq4hspQi
            IAacNpYned8yKZeSWD+20l4B1fmhZUBRRrnIwWpxZPprOHuitrWASecM7FzG2pe+
            7uzZAGcEzSFS6CFB6FT5CXEoD+ufdX8J9wwhcEQwNB3q3M1S+6/O91aNSfWK8E+1
            uJyeHdX5FFkKN15R0w95
            =ZzIX
            -----END PGP MESSAGE-----
          fp: 1CFC8FF236EC0896
    encrypted_regex: ([Pp]assword)
    version: 3.7.3
