# -- host
ansible_host: 192.168.253.4
ansible_user: ubuntu
ansible_password: ENC[AES256_GCM,data:oMqG1kKLKQU=,iv:7lPVGx+ILflrdmoeObecIisr9YW2LS5LtGrJKy7cPOw=,tag:x1iCWd0+UjiV7niPpv5egQ==,type:str]
ansible_become_password: ENC[AES256_GCM,data:BuRl21FZu29z3j0Q5BfiauKGZYqEKw==,iv:8Xy9RJz5oE0M/g59vIt5AIJiReYQbqPfvI/E1cT1GrU=,tag:siFxH9N2NocwagJkREnlWA==,type:str]
# -- zfs
zfs_install_update: false
zfs_create_pools: true
zfs_create_filesystems: true
zfs_manage_filesystem_permissions: true
zfs_pools:
    - name: hdd-pool
      action: create
      compression: lz4
      devices:
        - ata-ST4000VN008-2DR166_ZDH95W58
        - ata-ST4000VN008-2DR166_ZDH93J1E
      type: mirror
      state: present
zfs_filesystems:
    - name: garden
      pool: hdd-pool
      quota: 1T
      mountpoint: /hdd-pool/garden
      sharenfs: no_subtree_check,all_squash,rw=@192.168.255.0/24
      owner: nobody
      group: nogroup
      state: present
    - name: shed
      pool: hdd-pool
      quota: 2T
      mountpoint: /hdd-pool/shed
      sharenfs: no_subtree_check,all_squash,rw=@192.168.253.0/24
      owner: nobody
      group: nogroup
      state: present
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-06-19T16:09:25Z"
    mac: ENC[AES256_GCM,data:bwCij8XHRV8TCw2qmtkDVrO7Wpm7q8kGPOUbz4LaYxXr7zMajDBvCWp8GlA27nHQCkKHkPY/cskaX3rbz9SHqxGYxKCGrpmZBwlddRXk65crb54eLMngE3BidWBUTvp0QpkMyEZNV7wblxQVdwrQMhPxMqhPT0E3iQFs7Ii877A=,iv:u3ufdrwGcFfA3GZ0izXO3dMYcKm3smdNkh9BN0suzB0=,tag:OPL6AXShH0t7jUWVCZsa6g==,type:str]
    pgp:
        - created_at: "2022-06-19T16:09:24Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMAxz8j/I27AiWAQv9H/MuvE31Z/VVj4enYBrH12t8V2F/Qt/z5/mpQ042hWUe
            s2xTVGj6bOVZQi6MHJFB1NvTumj6CysP/9KRLu7l9gkYfQXvo/9Giv+6Y8Uz9rHs
            uhnDMlGz1WZB2DIeKpBmE2GEjpwLGIpCaf6OB2oj6tG20PYVhEIRTn2Ke6i7UDpd
            wFOhGuku94S5nKdN/ueR1/TPOB4guIkln8os6uFONyU3WUpTHkWbdKGgtclleH4C
            UT+I9R4c44aBOI2vmNCaMD/ui0U2rh2LM8GBzJlSLU/p8nX+01H6Lc35dykTuntp
            YKXGmJMmUPIeO+k6fxtvp50RD4p6282pve4Hg1KxJy9tOZCcockrwtClVlJ0lTBE
            21eLySQRtMDXN5cUwCNNsgJjVrO9IqllBsK2fM+E9toBPMsXhmxGbBCtAvLEgt+G
            JBP6Xtct0j3S3AXvAXgUixq6j1vREchujSYySs3sYLa9PRcBWgbErFpWfKJKvZiu
            e7QnDhLCoq6MW1Y0wl2H0lwBygdNfgMhyUGxy1DJ6aPyn33HszrC9U6MTRQbE7Ws
            G3ObhXRGEZ33OWL8AEwhkaUcn5m7f29Stb4vrxfFFw0t4F2KhWDgVA1QdcESLnWZ
            HNz2j+jkRQjub8bX8A==
            =Hhbi
            -----END PGP MESSAGE-----
          fp: 1CFC8FF236EC0896
    encrypted_regex: ([Pp]assword)
    version: 3.7.3
