---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: monitor
  name: grafana-data
spec:
  storageClassName: ceph-fs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100M
