---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  namespace: ingress-nginx
  name: ingress-nginx
spec:
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        namespace: flux-system
        name: ingress-nginx
      # renovate: registryUrl=https://kubernetes.github.io/ingress-nginx
      chart: ingress-nginx
      version: 4.1.2
  interval: 1h
  values:
    controller:
      extraArgs:
        default-ssl-certificate: cert-manager/wildcard-certificate-secret
      publishService:
        enabled: true
      service:
        type: LoadBalancer
        loadBalancerIP: 192.168.253.100
        externalTrafficPolicy: Local
      replicaCount: 2
      updateStrategy:
        type: RollingUpdate
        rollingUpdate:
          maxUnavailable: 1
          maxSurge: 1
      resources:
        limits:
          cpu: 300m
          memory: 512Mi
        requests:
          cpu: 100m
          memory: 128Mi

    defaultBackend:
      enabled: false

