---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  namespace: flux-system
  name: crd
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./shed-cluster/crd
  interval: 10m0s
  prune: false
  dependsOn:
    - name: source