---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: minio
  name: minio-data
spec:
  storageClassName: nfs-hdd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Ti
