#- kube-vip secrets
# md5 hashed password
kubevip_router_password: ENC[AES256_GCM,data:dHd5eQ5A1tRv7FMpspd4VMJpInaNk1FXIhGurkKwrEs=,iv:2IkCPGJFCrkFE22RLKR2qWCnHBXSOoZ0BbBUm9tXWVo=,tag:YymN9eRofEns6GEDMOHjvg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-04-26T08:07:48Z"
    mac: ENC[AES256_GCM,data:lTU4cOYR3YUlni0U/tE0qtNMLaxlQszNwEb5AnDa0TUH+3lOWDDx/fEA0W05H7xBn5O8u5+/wn6K224TOpGD8I6pAjO9lCk+Qb9uCUO7JWAiYaAVPINr3p9J3tAWKqjQEa/fta0S7kQtrSZgriUOAiRfbF4aiuuaATCTlrdVW2c=,iv:BukfvgitdIcGhlUyoRn72H1vW714P1Qsf8Skk5dztHA=,tag:oTE8ZgpoJrafxDnbmlNknw==,type:str]
    pgp:
        - created_at: "2022-04-26T08:07:33Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQMOA7Xwm0UuZgqEEAv/SIttNg//uoZ/BVufvJ7GfKg+GGuqVKP/+x5r0MgRdT94
            0zX21/FKUY4CI5g+uSV/Gm6cbrmZk3HitCXfg6wtNFEEGdHLCKZPcG+NmeJUoD+I
            jJ0yQVyt83MGkjvUuztPr4+uL1elSipm4JnivxcHgrV2TxY/f8lHtVmn1qv5jbc7
            MckaA7gUiPqyeRS6mR0722vMoMze3NHFiYu7S2Sb/saxOKT/B1FuDlkJO2MAQohA
            KDfTAXQ5rrDgrSum80znfGrW1yUNP995YZqauOavCSkJwLojzlKEVqKO27SzAl5W
            zXqb8ZhNJVPUegc3wcm0mlNKGgJOCxlHA9eNyQ9/YWKbRF2jHISS3SRbqnZPN4TR
            hl3OAzwws1vxfJFmx60daPBTcry39dPSEuRrTjVhKEqMFqIzi3ek/2jOZb5dk5EW
            jvfr/GDaGh/s1aV7nSbHwFE1QJlwwzJ8SfOBRSuxJDrMNEJk4aeWS3ePhVw9z3gk
            3+eRG3ODz9pajIMT9k/2C/95uriu3ZAq2YHwRPt+i+Vm8brt4193uGAHFzof4X2R
            ngZwx/sZWQvpoVT5mATUoacNHYDGMGEI7E9wlCFFJCPuWCyJ9sVIe/WPPKsTp9GB
            IfBzEdHLJ30UFuZHBSStTf/nHnDxxYknN4h22zYoLbqLg3iFGSYjB6zLxWX3VLVj
            XZMHsp+xPW5umLy/aB0uTM3PbaLMD+kvpzOKY1XMbmmAlUkorFJysYVpL+qpTiqY
            7B8rvaBKjTP4mViG0ZKxCsWwN2rI146RHlHsy+z8B4inmg5tTTMkF/qUIhqyp/fQ
            2Q3XhfZRr0PcLOBSt4AU9Nml/ALFwdl+VxKvsohhv+jfYanutwudtek7QGb3G0La
            zwLlLxLMLLelwA+hBuFqVo2Fm8PZCPE9KSIaMq8SwkYpX/usgItmTNupCbvJLHH9
            nyQYW8VhXxKhtaxLh+HfbsedPs0GX+OxeVSvafUW9T1H9ls/A2DUUp6XylT9y9DK
            wJYh/v8t4P44zIaHE4mTLRrSXAF1lz4y3JG23turPKKIy0EsNjdf4L3GmcZMndHP
            h+5iWyqvUXhLQJ3HBzzPARsw/s8bGpUpej+0pei1+RVmL5CcY+8YWNW3EgQWDgW+
            Z0NWtvnfDH9rJCuYDmo1
            =1Vaj
            -----END PGP MESSAGE-----
          fp: B5F09B452E660A84
    encrypted_regex: ([Pp]assword)
    version: 3.7.2
