# pve group name and cluster name
pve_group: nuc11pve
# use default software watchdog
pve_watchdog: nmi_watchdog
pve_cluster_enabled: true
pve_reboot_on_kernel_update: false
pve_remove_old_kernels: false
pve_roles:
    - name: Terraform-provisioner
      privileges:
        - VM.Allocate
        - VM.Migrate
        - VM.Clone
        - VM.Config.CDROM
        - VM.Config.CPU
        - VM.Config.Cloudinit
        - VM.Config.Disk
        - VM.Config.HWType
        - VM.Config.Memory
        - VM.Config.Network
        - VM.Config.Options
        - VM.Monitor
        - VM.Audit
        - VM.PowerMgmt
        - Datastore.AllocateSpace
        - Datastore.Audit
pve_users:
    - name: tf-prov@pve
      password: ENC[AES256_GCM,data:a33Rk+Uq8Ay+RAO602cHHw==,iv:BCWG6yOZr/i7Fprcw+6Yd49JJhXHQJuTBOygG2w5ZEs=,tag:/SQQqibl96ct2cWVjMmYzA==,type:str]
    - name: k8s-exporter@pve
      password: ENC[AES256_GCM,data:6EjwDYCPXiZUbCjsQvjrwT5VjVaV,iv:8jcEmtQO+d0aEPM5kQPwD/NfN0yFzqz2nl43wUU8Wrc=,tag:VYoDs5cEv9D3KtCVGfyfDA==,type:str]
pve_acls:
    - path: /
      roles:
        - Terraform-provisioner
      users:
        - tf-prov@pve
    - path: /
      roles:
        - PVEAuditor
      users:
        - k8s-exporter@pve
# ceph public network
pve_ceph_network: 192.168.254.0/16
# ceph internal network
pve_ceph_cluster_network: 10.10.10.0/24
pve_ceph_enabled: true
pve_ceph_osds:
    - device: /dev/nvme0n1
    - device: /dev/sda4
pve_ceph_crush_rules:
    - name: ssd-rule
      class: ssd
      type: host
      min-size: 2
      max-size: 3
    - name: nvme-rule
      class: nvme
      type: host
      min-size: 2
      max-size: 3
pve_ceph_pools:
    - name: vm-ssd
      rule: ssd-rule
      application: rbd
      pgs: 32
      autoscale_mode: "on"
      storage: true
    - name: vm-nvme
      rule: nvme-rule
      application: rbd
      pgs: 32
      autoscale_mode: "on"
      storage: true
pve_ceph_fs:
    - name: k8s-storage-ssd
      rule: ssd-rule
      pgs: 32
      storage: false
      mountpoint: /srv/proxmox/k8s-storage-ssd
    - name: k8s-storage-nvme
      rule: nvme-rule
      pgs: 32
      storage: false
      mountpoint: /srv/proxmox/k8s-storage-nvme
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-05-09T09:41:15Z"
    mac: ENC[AES256_GCM,data:eZNSH+dqf7ZOf8tVKGoQLp+13Bc0CvoRPeEy00v5hhofS34N+oG+7dQKtUNybRsMKLjozdQRqrzpA4eVbu1bckbUhgyXIuebCv6pRDbZygmGR9JPkFRlX9Y6ytiCogcmt0l78Q4qW75dAxArVm0k20Imi87r1UpNg++st1PM4Ck=,iv:Z+40d2hW0NGouI+/8LUs7p0Qpg2V7NINpogz9mPtuAE=,tag:e4LSip1AiCXzMAijWYnUXQ==,type:str]
    pgp:
        - created_at: "2022-05-09T09:36:06Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQMOA7Xwm0UuZgqEEAv/RAtKHKG9YkNnQpKIKAAxq9aByE/6roLz+tsP7AczqZfs
            8vMvXsEpLpI54fv2kbjDhk+P+8Y6i4eKM6U3tbPsm9aN2jSRN4T/hvX43l+M2B0S
            L1kYrUb5XlB4ckX4VyxgU03w5C8fi8C+W5buefl8Yb++Webwmbztao5zueERmV+w
            tw4yrOKeRnzzJoa9/QN5DxRH/lv+jhx8gVVD93TcxQFYigUE9POudh9Ffq76UsZX
            SeYn+W1qCF+iH+aeZUW5ScXC9ReaVqtDOgoeHSWMvl6Myap9yjXNFif9eCLt3Puk
            g2Xle09MZzeI2l5EeEwasG+Ugnt8oUse+nZZ4ZiX3/JmnlxsQAj+Tg+ugS25NcsH
            VVxPU8z0Q9ISFVhHEa0y/8E64Jc5zTcZ0XBKuh3eMdVJ7/HrSk/GbiWcf8ZatUKg
            ChUE2drVIPJ6k3O3sqNJEFoAP7RNXzp88knx9ocSN1S1tORHk+s+7HirJ+EN/KoE
            uCooWXlmgaERPHAFP8f6DACF9JYIRFC3F8AZU4q5ZsH5X4gM/9L3Bz06OnWDqy7A
            knunx1YtNnxRjvzItLS9syFAFSWFa7Bgasz2iI3gcZ9EPF7FyfG3MGnDLIovZhRs
            6PseRi64wXZj+PTHus7/azYnUlOoJDvwzjFBga0Nnx+VVjHqeML+/LiCL14a9b9W
            cRoXHQsuMT3lugcYkbFsF7kTWOQfblw5VFcnfToz6ld0mO1PugsMiqU3Z6FfGIJf
            Cjl4ZQycXGfmkbTHmjzEYAdR2GCQRWzZzqZfdVDT0NeRbEZqiqPqTI7UxmaxZG9+
            A7TZIcAFHOYGcW7/HKj6heB4cbra0ByJ2y1YqaTP5ofFMNLHz6AcXWDYH2dWlXPp
            8ajS/8u6/TKh5vodlGaspbQC3nQy4Jfmmd/4jHRB99fVjaLMBAmnI4EHYMzY1aNF
            xDj6z1ogEWSFwcCA5vsbsi5zQTKj2UkG5amkqyfSUIwh5fNvWr7qlrPVSZBVykHC
            na5ofA5bvA/7kLgA4cSe07vSXAET0DOYjlew6lVIzE1IFwM6pv4R9mwhAFH4ZaZ8
            bn9Aj+Hj1UluoaOeUTU+g8MbxMqjvTAV/B9YEowXc8OtfN5J/Hjie8ej+/WGPsJd
            gFTSkws3dB7k6X4A5lFS
            =MPUU
            -----END PGP MESSAGE-----
          fp: B5F09B452E660A84
    encrypted_regex: ([Pp]assword)
    version: 3.7.2
