# pve group name and cluster name
pve_group: nuc11pve
# use default software watchdog
pve_watchdog: nmi_watchdog
pve_cluster_enabled: true
pve_reboot_on_kernel_update: false
pve_remove_old_kernels: false
pve_roles:
    - name: Terraform-provisioner
      privileges:
        - VM.Allocate
        - VM.Migrate
        - VM.Clone
        - VM.Config.CDROM
        - VM.Config.CPU
        - VM.Config.Cloudinit
        - VM.Config.Disk
        - VM.Config.HWType
        - VM.Config.Memory
        - VM.Config.Network
        - VM.Config.Options
        - VM.Monitor
        - VM.Audit
        - VM.PowerMgmt
        - Datastore.AllocateSpace
        - Datastore.Audit
        - Sys.Audit
        - Sys.Console
pve_users:
    - name: tf-prov@pve
      password: ENC[AES256_GCM,data:bv3GU9UbrcElVMHjWi+pow==,iv:P/z1eFlvTGg7qMce3G/C4nERCrDfHVz+EzY3ML+piaM=,tag:p+qr5DBOjgtVAAIQEtM6Bw==,type:str]
    - name: k8s-exporter@pve
      password: ENC[AES256_GCM,data:M38F65doU8fV2+5cNwsdjQwWUvID,iv:Syo7m1DyjiXQCvyshuz7u4mNL8M8kByyid8g6W8aKU4=,tag:cMg4EWhb9fbx8mj0rZWXPw==,type:str]
pve_acls:
    - path: /
      roles:
        - Terraform-provisioner
      users:
        - tf-prov@pve
    - path: /
      roles:
        - PVEAuditor
      users:
        - k8s-exporter@pve
# ceph public network
pve_ceph_network: 192.168.254.0/16
# ceph internal network
pve_ceph_cluster_network: 10.10.10.0/24
pve_ceph_enabled: true
pve_ceph_osds:
    - device: /dev/nvme0n1
    - device: /dev/sda4
pve_ceph_crush_rules:
    - name: ssd-rule
      class: ssd
      type: host
      min-size: 2
      max-size: 3
    - name: nvme-rule
      class: nvme
      type: host
      min-size: 2
      max-size: 3
pve_ceph_pools:
    - name: vm-ssd
      rule: ssd-rule
      application: rbd
      pgs: 32
      autoscale_mode: "on"
      storage: true
    - name: vm-nvme
      rule: nvme-rule
      application: rbd
      pgs: 32
      autoscale_mode: "on"
      storage: true
pve_ceph_fs:
    - name: k8s-storage-ssd
      rule: ssd-rule
      pgs: 32
      storage: false
      mountpoint: /srv/proxmox/k8s-storage-ssd
    - name: k8s-storage-nvme
      rule: nvme-rule
      pgs: 32
      storage: false
      mountpoint: /srv/proxmox/k8s-storage-nvme
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-05-17T17:33:28Z"
    mac: ENC[AES256_GCM,data:w1lmwCkcWoJYVLotCgg7r2INFf1LD8WK9NTGSYYKn6KOrddGPOKS/inl7Nl/ivMKrJ8LUg+mS2bRoub5gQZdL+uSRIhwOUytJlXtkqXMlB6KcghszFcaYxX57yVYAycwhHdTG2vIS3L5qHfC/UrcNzZ+vE81SC5Q0HM3FG6Am14=,iv:CHHC8bpK5cCLMAFBji5BCL8BzD4BK/fqKyYlwxGBwhE=,tag:ZIUXUvT4R51/Ru2UJUoANQ==,type:str]
    pgp:
        - created_at: "2022-05-17T17:33:27Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQMOA7Xwm0UuZgqEEAwAjkQxgg/e7GqYxElRzMgRmWGinDEyVUEAXiwMryuYe4uN
            miyQ50tkRudufzN4bhIAZj1gXc4Z9RWnGVRxEXqXIKQt0jkhUcdMZKjeOSC7MdBQ
            VkTo5pDjfd1+DU/99Fo1rtY657vFMWlGbGpzOSUm4/eg5nTru9nXg/ASDyMUXYVL
            fV6ze3A5htZWkZq2GzNRlEvE1ZrvEn6M8320DOuGW8NZSxktqEIVb2ywzAAsAbXc
            haOinMLKQcSwztvsRH4Sa/Z3eE47zNewtMIPYN1oktAZvVvinvTBJ0ljKICSAS/T
            vnoiKEszv6ej/ZQNfeQra1t86onN6E9rslNlNivmfjbOt3Lj8fjKgb3JRfwAs8z5
            EpM5DeBQfewsElSnkbRTEeOWFgxBbPrkCPJvsPoj4OPfmRx/sBRfXw1o/ePfo+Qs
            iiQwEgm+9sKa3iR+P28SBZYmKTZ6BTmaE4HD9h3hMK4V16zrAlMvnJq3xBWojtIq
            LjyztimxbY7SQKEA81/XC/90Ci80oMrnux6RHCeJauZvx3ycsZGXPFOCdbPHa7Cw
            XX2vdLnpl85x5c9zNAuajoNvzeW+x8KBJVjKd36cKiqXKfj8t9YBsOZ/+k+FgBbk
            0A3G5OWMNjezNKthchq+NpjaBL6naJtMNaoWKCt/j3+WqIvDGrvx8ZCYCvcIp61h
            HnzOGWHJBz1QGFz9nyjIu0PCO2wrAWcd5tgjWqpR3fx1J8fDDZpzq2NK8wQ/dJM2
            9CdOmtl1ksbEkDp+C4kl6VjIR+Iwwn/46bG3wJOqrShALGuHXLE2rzeRBfnmo3dw
            Fr5jcCXG3fXIAaQM/wDtkqqniB+Wv5yx84+C2CnvL1HrrlRcLJ96k3129svjTiFr
            zYMNNzivtYAFYN7KiqbsPrURmXT9S+vuQbw6Im78EjxYjmRHu01S3mE9kKe/wDBF
            5Up6yJIRTz4ei+IuBgUhbHO3RXBJvg+OxzTGCthHmIC7f1SeguJaAsZaj8LGbjHd
            oGM59iX2bwibcA3tnBW9G9fSXgFMWzLd1HapVmVhyBwjySm2lVxXeVPM6A8H7A1p
            DW6OYVoB1btuuH66iaQsvxD8H0hgJuBQaFvHUf1haYq3x1qzplXPVbzHlgNKoq4T
            h/p+8yBAaEkY7EyOZkfhM6I=
            =VADP
            -----END PGP MESSAGE-----
          fp: B5F09B452E660A84
    encrypted_regex: ([Pp]assword)
    version: 3.7.2
