# pve group name and cluster name
pve_group: nuc11pve
# use default software watchdog
pve_watchdog: nmi_watchdog
pve_cluster_enabled: true
pve_reboot_on_kernel_update: false
pve_remove_old_kernels: false
pve_roles:
    - name: Terraform-provisioner
      privileges:
        - VM.Allocate
        - VM.Migrate
        - VM.Clone
        - VM.Config.CDROM
        - VM.Config.CPU
        - VM.Config.Cloudinit
        - VM.Config.Disk
        - VM.Config.HWType
        - VM.Config.Memory
        - VM.Config.Network
        - VM.Config.Options
        - VM.Monitor
        - VM.Audit
        - VM.PowerMgmt
        - Datastore.AllocateSpace
        - Datastore.Audit
pve_users:
    - name: tf-prov@pve
      password: ENC[AES256_GCM,data:TfF/0A9sZ+9HMOW5szzUEw==,iv:cIBz7gFauqt0rwzKkAsJVaW/RrD3ewRl5DAcxGiS0os=,tag:3nJDnYgv3x5zFoO64scr6g==,type:str]
pve_acls:
    - path: /
      roles:
        - Terraform-provisioner
      users:
        - tf-prov@pve
# # ceph public network
# pve_ceph_network: 192.168.254.0/16
# # ceph internal network
# pve_ceph_cluster_network: 10.10.10.0/24
pve_ceph_enabled: true
pve_ceph_osds:
    - device: /dev/nvme0n1
    - device: /dev/sda4
pve_ceph_crush_rules:
    - name: ssd-rule
      class: ssd
      type: host
      min-size: 2
      max-size: 3
    - name: nvme-rule
      class: nvme
      type: host
      min-size: 2
      max-size: 3
pve_ceph_pools:
    - name: vm-ssd
      rule: ssd-rule
      application: rbd
      pgs: 32
      autoscale_mode: "on"
      storage: true
    - name: vm-nvme
      rule: nvme-rule
      application: rbd
      pgs: 32
      autoscale_mode: "on"
      storage: true
pve_ceph_fs:
    - name: k8s-storage-ssd
      rule: ssd-rule
      pgs: 32
      storage: false
      mountpoint: /srv/proxmox/k8s-storage-ssd
    - name: k8s-storage-nvme
      rule: nvme-rule
      pgs: 32
      storage: false
      mountpoint: /srv/proxmox/k8s-storage-nvme
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-04-08T07:14:29Z"
    mac: ENC[AES256_GCM,data:m929JdPrfJ4Inl8Ls3AaY6yHCQbm1v6DHmpA9nWPgw7QXq+3hKl6Unp+JTUhlPtKmloUTE8TJaFfn+m5t7u+G+iKLDNYXPxxTUjHKhr6YMoN/Ns/0fDg4of0tOunloi+YGdH5BEa0ccU62/w6gim1b7FqSJUNuDro6v1GbpaJRM=,iv:1IdvkrXE+k1mJOgm69ZrF264r4ce36+qaLS/XJfxp80=,tag:wQaXel0/Jds7GZ9cqEyePA==,type:str]
    pgp:
        - created_at: "2022-04-08T07:14:27Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQMOA7Xwm0UuZgqEEAv9GLCq121WCHpK//gNnqJnSLeiJPqSbSZBx+4Fd2IvaoFJ
            Y17IxpxAeYzmXtiDZRC+QnFu1KYMdNWo78R1FmOLXklyygc8hWZe6YoXG2khqcXA
            IdnrdPeMvc+oSxyKQRKonpiPKO7FGao4gB4MBFBrltnsfzMqFeCVwFIKhRDJbK9L
            wcWvJPmMe4S0x+8F7mF/3gqLuZAO+O04BOz0MYRRozUo9pF6BbbihYnAGOJvRrFv
            02SL2aoJgR0ic6v903m1VqJwuD5BOb5lCeo5lPcKXEdPzYC/hs/4d8V2RBeF1/1D
            Q6ocYpu/t+1NW+L1vSAZycUUprIBVLfXqdgAb+SdaRVx0duuVpqQdjO5Iejt1gzj
            XpPQt0/BX25csUrHPXmB117MHekMeQhU7qfdAQkoqJrpE9WZNye5+Iq+wKCBpQIa
            OR6uCWWhkIuVbDxolwZG55fowF1mrDwFkVC+PGAtLoxE3uBSUu4/1tOwcw4qd6H5
            c4qwQYTcrCDvUlwnknnJDADI8RGb7aTV2/mzfiH8GDJrYnWDgxuDOa2bgJe+8fjk
            JJ2X+H6sST/B9uiML10tff3j0Rh17HnYPAKV7saG+dG2GN5wi0u6PmAET/wPwB1P
            cYth63nN/pQTpGcGGA6lSglXFZH1B4eCq47ufUo3qhtLT+Oh35PertQJut/hJSfX
            oxE/Kkd8pL7wfgCeL+9/KRPHljskYu9odGRAjrvv/fX1L77jHKcQZNc6yihgG6bX
            HwtF13JuMaTqJ+bo0UOfwyaubGBWju0J7+lbs2DWFrrXYRSFrBzuzqaY5oKcXHk9
            Kq3r/R076FibffdH8KiWwK+x9jC6nHREQFwES9vAINl7wFP8bcJeaY7bTTmIjo4L
            Teq+VmIft42+bxz+kVk/9n+l9WArRAhNaIw+sgPtWlSG072qlIjOFdCYVObJtgsf
            LHxQhkVAhprzcpZ6VJGfb1ranFAUUoUPonSwDswqLTMddtSF59X+q71JebnxmYqW
            h0jETT3V0//b/Pwyxp8jFw7SXgEnKcgYcULcEeHmbfFlHHe0ljmIe3dNFdZyrg+c
            eBT+tpIsk8hIfuYJlrMMT0ApjrwNEqwfGiou4y1nfjfEMCk81kycGG7AwPfFcf/K
            +Dynq86PR0pN20X+JIF3i/E=
            =E7A7
            -----END PGP MESSAGE-----
          fp: B5F09B452E660A84
    encrypted_regex: ([Pp]assword)
    version: 3.7.2
