apiVersion: v1
kind: Secret
metadata:
    namespace: monitor
    name: mimir-secret
type: Opaque
stringData:
    MIMIR_S3_ACCESS_ID: ENC[AES256_GCM,data:0r3/EvQ=,iv:YJjXigiLH680c8zOn36Y8Z9B+9LiziZkGhEDXpUi2Y4=,tag:j6d9rF0qoTAKQApjHoQuSw==,type:str]
    MIMIR_S3_ACCESS_KEY: ENC[AES256_GCM,data:8w04Wqr7lUs=,iv:vUXRei4j2/ZEWl+tGdWvY8VCMIqRos39mPv4/B0ofNk=,tag:6zRhh8pH9NmP/f8zQryW0A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-06-19T16:19:28Z"
    mac: ENC[AES256_GCM,data:NjdplMmngxDtNGg7B1bAP44O/HsH54LyJFrKdzyP4vpB0WzrZuiHjWoMg/Qcif0dgcSC6bV4wom8arC5WbaUZSb4g8BIMyseH3d0sYi8/Bjc+1oAROINJWM7NrYwyF87nPdrWik67zWp0yaXdOpHTXrWy1SdKs/MSiQAvGouINQ=,iv:OQvmCvxHbs7iqVQIbEFKVPdVwfJPFxoA2KmNOfP4CVA=,tag:jqct7aqlh6XZ3VxNyYf84Q==,type:str]
    pgp:
        - created_at: "2022-06-19T16:19:27Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMAxz8j/I27AiWAQv+KPyzMTkyJeJWLgef83IvhQDv4Tl7lMkiWR3Sy4B+0IEl
            ueEaOyExFqfFBYLJe0iNX3Th52XKsRq5p0y9FHQW49W8Es4VKtoKjestVynU43vZ
            kOk6MZQ+AZhwx8hXMsuOceclENRAo3d9j4zekH04vSEiTV0haNypmMQ+6CiJe8tz
            YhbbBL9qkzygUoQmO/nMdCt5kTHK48SFO9yWvAmJILzu6BFaMv+Tz3zy4fDNby/5
            fhiotORw+NHHvI/jAcre6EWIhnottY1+8h9FwgoldHEs/0+hRcjuo2MfA3hWoXdj
            kiWFCW5tcyoOL0x68BwSTEO7haVwzlqf7TkW9ErG/mYZYo8LjQmyIfzYecXrRo+S
            13OWRxc+mPOLVQmmCEfEgtg64PGAbVqGPM+iVE5EKslfWgu5IyLV6GY9cC5P/Dx+
            6umcdMCM0efOAmJcHRljYh94Q8a3mGsZs6UvNpxZ+LBnzaqsSHIxiB3Yt+V1a6GZ
            3lJlFV6k132Cfgxm98CR0l4BIYkxToNaG50+hP4EBitTMP5ZxdHWa1Oo87ZaiRFm
            +MUm0QZvbCgicM9pVn6+07g2TSyrXns7gSkGEW3766i2vZR4tCWbWMGjQ7cnmBNR
            RWvzPQlulPBbKI5T+BPF
            =UaiK
            -----END PGP MESSAGE-----
          fp: 1CFC8FF236EC0896
    encrypted_regex: (^data$|^stringData$|user|[Pp]assword|userDatabase)
    version: 3.7.3
