- hosts: all
  tags: [prep]
  roles:
    - name: shed

- hosts: zfs
  tags: [zfs]
  roles:
    - become: true
      role: mrlesmithjr.zfs

- hosts: all
  tags: [k3s]
  roles:
    - name: xanmanning.k3s
