---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  # disable flux env substitute and use config expand
  labels:
    kustomize.toolkit.fluxcd.io/substitute: disabled
  namespace: monitor
  name: loki
spec:
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        namespace: flux-system
        name: grafana
      # renovate: registryUrl=https://grafana.github.io/helm-charts
      chart: loki-simple-scalable
      version: 1.4.1
  interval: 1h
  values:
    loki:
      readinessProbe:
        initialDelaySeconds: 20
        
      # -- Config
      # do not use default config
      config: ""

      # /etc/loki/config/config.yaml
      # reference: https://grafana.com/docs/loki/latest/configuration
      structuredConfig:
        server:
          http_listen_port: 3100
          grpc_listen_port: 9095

        # adguard DNS blocks this creating a lot of error log
        analytics:
          reporting_enabled: false

        # ???
        memberlist:
          join_members:
            - loki-memberlist

        # indexes data storge
        schema_config:
          configs:
            # qoute of time is required 
            # or flux (maybe json-yaml library) will change it to TZ format
            - from: "2022-06-08" 
              store: boltdb-shipper
              object_store: aws
              schema: v11
              index:
                prefix: loki_index_
                period: 24h
        common:
          path_prefix: /var/loki
        # chunks data storage
        storage_config:
          aws:
            endpoint: minio.minio.svc:9000
            bucketnames: loki-chunk
            access_key_id: ${LOKI_S3_ACCESS_ID}
            secret_access_key: ${LOKI_S3_ACCESS_KEY}
            insecure: true
            sse_encryption: false
            s3forcepathstyle: true
        # ruler storage
        ruler:
          storage:
            type: s3
            s3:
              endpoint: minio.minio.svc:9000
              bucketnames: loki-ruler
              access_key_id: ${LOKI_S3_ACCESS_ID}
              secret_access_key: ${LOKI_S3_ACCESS_KEY}
              insecure: true
              sse_encryption: false
              s3forcepathstyle: true

    # -- Workloads
    write:
      replicas: 3
      resources: 
        limits:
          cpu: 200m
          memory: 128Mi
        requests:
          cpu: 100m
          memory: 64Mi
      persistence:
        size: 10Gi
        storageClass: ceph-fs
      extraArgs:
        - -config.expand-env=true
      extraEnvFrom:
        - secretRef:
            name: loki-secret
    read:
      replicas: 1
      resources: 
        limits:
          cpu: 200m
          memory: 128Mi
        requests:
          cpu: 100m
          memory: 64Mi
      persistence:
        size: 10Gi
        storageClass: ceph-fs
      extraArgs:
        - -config.expand-env=true
      extraEnvFrom:
        - secretRef:
            name: loki-secret
    gateway:
      enabled: false
    tokengen:
      enabled: false
