---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: cert-manager
  name: cert-manager
spec:
  namespaceSelector:
    matchNames:
      - cert-manager
  selector:
    matchLabels:
      app.kubernetes.io/name: cert-manager
  endpoints:
    - port: metrics
      interval: 60s
