roles:
  - name: xanmanning.k3s
    version: v3.1.1
  - name: lae.proxmox
    version: v1.7.0
  - name: mrlesmithjr.zfs
    version: master
    
collections:
  - name: community.general
    version: 4.7.0
  - name: community.sops
    version: 1.1.0
  - name: devsec.hardening
    version: 7.14.1