# -- shed
shed_hostname: "{{ inventory_hostname }}"
shed_public_key: "https://github.com/timtorchen.keys"
shed_timezone: Asia/Taipei
shed_apt_repositories: []
shed_install_packages:
  - unattended-upgrades
  - net-tools
  - trash-cli
  - nfs-common
  - smartmontools
  - vim
  # zfs package
  - zfsutils-linux
  - nfs-kernel-server
  # workaround for Ubuntu 22.04 calico panic
  # https://github.com/projectcalico/calico/issues/5410
  - linux-modules-extra-raspi
shed_remove_packages:
  - snapd
# -- ssh hardening
ssh_server_password_login: false
ssh_permit_root_login: 'no'
sftp_enabled: true
ssh_x11_forwarding: true