---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  namespace: metallb-system
  name: metallb
spec:
  interval: 1h
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        namespace: flux-system
        name: metallb
      version: 0.12.1
      # renovate: registryUrl=https://metallb.github.io/metallb
      chart: metallb
  values:
    controller:
      enabled: true
    speaker:
      enabled: true
    existingConfigMap: metallb-config